[[redirects]]
  from = "/attendance-table"
  to = "/"

  [[redirects]]
    from = "/attendance-form"
    to = "/attendance-form"

  [[redirects]]
    from = "/register-user"
    to = "/register-user"

  [[redirects]]
    from = "/login"
    to = "/login"