[[redirects]]
  from = "/login"
  to = "/"

[[redirects]]
  from = "/attendance-form"
  to = "/"

[[redirects]]
  from = "/attendance-table"
  to = "/"

[[redirects]]
  from = "/register-user"
  to = "/"